#!/bin/bash                                                                                                                                                                                                       │
                                                                                                                                                                                                              │
just -f /usr/local/bin/sysctl-manager.just "$@" 
