---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: mess1-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
#base-image: ghcr.io/ublue-os/silverblue-main
# KO base-image: quay.io/fedora/fedora-coreos:stable
base-image: ghcr.io/ublue-os/ucore-minimal
image-version: stable # latest is also supported if you want new updates ASAP
#image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: script
    scripts:
      - setup.sh # example: run config/scripts/myscript.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
