---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: mess1-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
#base-image: ghcr.io/ublue-os/silverblue-main
# KO base-image: quay.io/fedora/fedora-coreos:stable
base-image: ghcr.io/ublue-os/ucore-minimal
#image-version: 41 # latest is also supported if you want new updates ASAP
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - micro
#      - starship
      - hyprland
#      - xdg-desktop-portal-hyprland
      - hyprpaper
#  YA ESTA    - hyprctl
#      - alacritty
      - vim
      - firefox
      - NetworkManager
      - network-manager-applet
#      - sddm
      - waybar
#  YA ESTA    - dunst
      - grim
#  YA ESTA    - slurp
      - mpv
#  YA ESTA    - pipewire-pulseaudio # Or just pipewire
#      - polkit-gnome
      - gnome-keyring
#  YA ESTA    - sudo
      - distrobox
      - fastfetch
      - gum
      - just
      - fzf
#      - dmenu
      - dolphin
      - cockpit
      - cockpit-files
      - cockpit-machines
      - cockpit-networkmanager
      - cockpit-ostree
      - cockpit-podman
      - cockpit-selinux
      - cockpit-storaged
      - cockpit-system 
#      - cockpit-tailscale
#    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      #- firefox
      #- firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix.
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans
      
    #  - type: default-flatpaks
    #    notify: true # Send notification after install/uninstall is finished (true/false)
    #    system:
    #      # If no repo information is specified, Flathub will be used by default
    #      install:
    #        #- org.mozilla.firefox
    #        #- org.gnome.Loupe
    #        - io.podman_desktop.PodmanDesktop
    #        - io.github.flattool.Warehouse
    #      remove:
            #- org.gnome.eog
    #    user: {} # Also add Flathub user repo, but no user packages

  - type: files
    files:
      - source: system
        destination: /

  #- type: script
    #snippets:
    #  - "curl https://example.com/examplebinary > /usr/bin/examplebinary" # example: download binary
    #  - "ln -sf /usr/bin/ld.bfd /etc/alternatives/ld && ln -sf /etc/alternatives/ld /usr/bin/ld" # example: ld alternatives symlink workaround
  #  scripts:
    #  - JBSetup.sh # example: run config/scripts/myscript.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

